import { jsPDF } from "jspdf";

const MARGIN = 14;
const PAGE_W = 210;
const PAGE_H = 297;
const FOOTER_Y = PAGE_H - 12;

function formatMoney(n) {
  return `Rs. ${Number(n).toFixed(2)}`;
}

/**
 * @param {{ sale: object, items: object[] }} data
 * @param {{ billerName?: string, billerId?: string }} [meta]
 */
export function generateSaleInvoicePdf({ sale, items }, meta = {}) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  let y = MARGIN;

  function ensureSpace(needed = 8) {
    if (y + needed > FOOTER_Y - 4) {
      doc.addPage();
      y = MARGIN;
    }
  }

  function textLine(str, x, size = 10, style = "normal", align = "left") {
    doc.setFontSize(size);
    doc.setFont("helvetica", style);
    doc.text(String(str), x, y, { align });
  }

  // Header
  doc.setFillColor(13, 148, 136);
  doc.rect(0, 0, PAGE_W, 28, "F");
  doc.setTextColor(255, 255, 255);
  textLine("PharmaSync ERP", MARGIN, 16, "bold");
  y += 5;
  textLine("Tax Invoice / Pharmacy Bill", MARGIN, 10, "normal");
  y = 36;
  doc.setTextColor(30, 41, 59);

  const billerLabel = meta.billerName || meta.billerId;
  const rows = [
    ["Invoice #", String(sale.id)],
    ["Date", sale.sale_date || "—"],
    ...(billerLabel ? [["Biller", billerLabel]] : []),
    [
      "Customer",
      sale.customer_name
        ? `${sale.customer_name}${sale.customer_phone ? ` · ${sale.customer_phone}` : ""}`
        : "Walk-in",
    ],
  ];
  if (sale.customer_address) rows.push(["Address", sale.customer_address]);

  rows.forEach(([label, value]) => {
    ensureSpace(10);
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.text(`${label}:`, MARGIN, y);
    doc.setFont("helvetica", "normal");
    const wrapped = doc.splitTextToSize(String(value), PAGE_W - MARGIN - 42);
    doc.text(wrapped, MARGIN + 32, y);
    y += Math.max(5, wrapped.length * 4.2);
  });

  y += 4;
  ensureSpace(14);

  // Table header
  doc.setFillColor(241, 245, 249);
  doc.rect(MARGIN, y - 4, PAGE_W - MARGIN * 2, 8, "F");
  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  const col = { product: MARGIN + 1, batch: 78, qty: 118, unit: 138, line: 168 };
  doc.text("Product", col.product, y);
  doc.text("Batch / Exp", col.batch, y);
  doc.text("Qty", col.qty, y, { align: "right" });
  doc.text("Unit", col.unit, y, { align: "right" });
  doc.text("Amount", PAGE_W - MARGIN, y, { align: "right" });
  y += 7;

  doc.setFont("helvetica", "normal");
  items.forEach((row) => {
    const lineTotal = Number(row.quantity) * Number(row.price);
    const nameLines = doc.splitTextToSize(row.product_name || "—", 62);
    const rowH = Math.max(6, nameLines.length * 4 + 2);
    ensureSpace(rowH + 2);

    doc.text(nameLines, col.product, y);
    doc.text(String(row.batch_no || "—"), col.batch, y);
    if (row.expiry_date) {
      doc.setFontSize(7);
      doc.setTextColor(100, 116, 139);
      doc.text(`Exp: ${String(row.expiry_date).slice(0, 10)}`, col.batch, y + 3.5);
      doc.setFontSize(8);
      doc.setTextColor(30, 41, 59);
    }
    doc.text(String(row.quantity), col.qty, y, { align: "right" });
    doc.text(formatMoney(row.price), col.unit, y, { align: "right" });
    doc.text(formatMoney(lineTotal), PAGE_W - MARGIN, y, { align: "right" });
    y += rowH;

    doc.setDrawColor(226, 232, 240);
    doc.line(MARGIN, y - 1, PAGE_W - MARGIN, y - 1);
  });

  y += 4;
  ensureSpace(12);
  doc.setDrawColor(13, 148, 136);
  doc.setLineWidth(0.4);
  doc.line(MARGIN, y, PAGE_W - MARGIN, y);
  y += 7;

  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("Grand total", MARGIN, y);
  doc.text(formatMoney(sale.total), PAGE_W - MARGIN, y, { align: "right" });

  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 116, 139);
  doc.text("Thank you for your purchase.", MARGIN, FOOTER_Y);
  doc.text("Generated by PharmaSync · Offline-first pharmacy ERP", MARGIN, FOOTER_Y + 4);

  const filename = `PharmaSync-invoice-${sale.id}.pdf`;
  doc.save(filename);
}
